export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "../.storybook/globals.css";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="grid place-items-center min-h-dvh">{children}</body>
    </html>
  );
}
